FROM python:3.12.3

ENV DEBIAN_FRONTEND="noninteractive"

# install app dependencies
RUN apt-get update && apt-get install -y
RUN mkdir /opt/productManager 
COPY . /opt/productManager

RUN pip3 install -r /opt/productManager/requirements.txt


RUN apt-get update && apt-get install -y \
    mariadb-server \
    && rm -rf /var/lib/apt/lists/*

RUN service mariadb start
RUN mariadb -e "CREATE DATABASE IF NOT EXISTS ${{ env.DJANGO_TEST_DATABASE }};"
RUN mariadb -e "CREATE USER IF NOT EXISTS '${{ env.DJANGO_TEST_USER }}'@'%' IDENTIFIED BY '${{ env.DJANGO_TEST_PASSWORD }}';"
RUN mariadb -e "GRANT ALL PRIVILEGES ON ${{ env.DJANGO_TEST_USER }}.* TO '${{ env.DJANGO_TEST_DATABASE }}'@'%';"
RUN mariadb -e "FLUSH PRIVILEGES;"