FROM python:3.12.3

ENV DEBIAN_FRONTEND="noninteractive"

# install app dependencies
RUN apt-get update && apt-get install -y
RUN mkdir /opt/productManager 
COPY . /opt/productManager

RUN pip3 install -r /opt/productManager/requirements.txt


RUN apt-get update && apt-get install -y \
    mariadb-server \
    && rm -rf /var/lib/apt/lists/*

ENV DJANGO_TEST_DATABASE=test
ENV DJANGO_TEST_USER=test
ENV DJANGO_TEST_PASSWORD=test

RUN service mariadb start && mariadb -e "CREATE DATABASE IF NOT EXISTS $DJANGO_TEST_DATABASE;" && \
    mariadb -e "CREATE USER IF NOT EXISTS '$DJANGO_TEST_USER'@'%' IDENTIFIED BY '$DJANGO_TEST_PASSWORD';" && \
    mariadb -e "GRANT ALL PRIVILEGES ON $DJANGO_TEST_USER.* TO '$DJANGO_TEST_DATABASE'@'%';" && \
    mariadb -e "FLUSH PRIVILEGES;"

WORKDIR /opt/productManager

ENTRYPOINT ["/bin/sh", "-c" , "service mariadb start && python3 manage.py test"]

