name: Django CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install Dependencies
      run: |
        echo "ls:"
        ls
        echo "build:"
        printenv
        echo "vars: ${{vars.DJANGO_TEST_DATABASE}}"
        docker build -t djangotestdocker --build-arg DJANGO_TEST_DATABASE=${{vars.DJANGO_TEST_DATABASE}} --build-arg DJANGO_TEST_USER=${{vars.DJANGO_TEST_USER}}  --build-arg DJANGO_TEST_PASSWORD=${{vars.DJANGO_TEST_PASSWORD}} -f Dockerfile_test .
        
