name: Django CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install Dependencies
      run: |
        echo "ls:"
        ls
        echo "build:"
        docker build -t djangotestdocker -f Dockerfile_test .
        
